### ISSUE TITLE
Receive notifications

### ISSUE THREAD

**Issue by pinapalmieri** [routetopa/spod#62] opened 2016-10-10 13:14 UTC
(Groningen: Feedbacks from students at Utrecht University (SPOD (v 1.4), 30-6-2016) )

As a moderator I noticed it would be helpful to receive notifications on other Platforms (Facebook, email, whatsapp etc) when there has been activity on SPOD and where. Now I checked regularly but it was always searching everywhere to see if something new occurred. This could be less time-consuming when you just see there and there has been activity

**Comment by lucavicidomini** [comment] 2016-10-20 14:39
Duplicate of #34

**Comment by lucavicidomini** [comment] 2016-10-20 14:49
Merged with #89

**Closed by lucavicidomini** 2016-10-20 14:49 UTC
Labels: enhancement, From Groningen, High
