### ISSUE TITLE
Receive email messages for personal messages

### ISSUE THREAD

**Issue by pinapalmieri** [routetopa/spod#58] opened 2016-10-10 11:16 UTC
(Groningen: Feedbacks from students at Utrecht University (SPOD (v 1.4),  30-6-2016) )

It is possible to receive email messages for personal messages, but not for new messages in Agora. It would be practical if this is also possible when new messages are being posted in Agora. In general the students note a wish for notifications, a reminder when someone reacts on your message in Agora

**Comment by lucavicidomini** [comment] 2016-10-20 14:39
Duplicate of #34

**Comment by lucavicidomini** [comment] 2016-10-20 14:49
Merged with #89

**Closed by lucavicidomini** 2016-10-20 14:49 UTC
Labels: enhancement, From Groningen, Normal
